public class GearSetClass {
	
    public Integer addMethod(Integer firstNumber, Integer secondNumber) {
        return firstNumber + secondNumber;
    }
    
    public Integer subtractMethod(Integer firstNumber, Integer secondNumber) {
        return firstNumber - secondNumber;
    }
    
    public Integer multiplyMethod(Integer firstNumber, Integer secondNumber) {
        return firstNumber * secondNumber;
	}
}