public class GeoForCity {
    
    public String name;
	public Local_names local_names;
	public Double lat;
	public Double lon;
	public String country;
	public String state;

	public class Local_names {
		public String hu;
		public String nl;
		public String sl;
		public String ja;
		public String hr;
		public String fr;
		public String et;
		public String sk;
		public String el;
		public String zh;
		public String it;
		public String tr;
		public String be;
		public String sr;
		public String ko;
		public String oc;
		public String ml;
		public String en;
		public String he;
		public String fi;
		public String pl;
		public String de;
		public String cs;
		public String hi;
		public String es;
		public String uk;
		public String eo;
		public String io;
		public String ru;
		public String ar;
		public String ur;
	}

	
	/*public static JSON2Apex parse(String json) {
		return (JSON2Apex) System.JSON.deserialize(json, JSON2Apex.class);
	}*/
}